drive_topic: "vesc/ackermann_cmd_mux/input/navigation"

odom_topic: "/pf/pose/odom"

scan_topic: "/scan"
safety_topic: "/vesc/low_level/ackermann_cmd_mux/input/safety"
safety_in_topic: "/vesc/high_level/ackermann_cmd_mux/output"
drive_comm_timeout: 0.5
scan_comm_timeout: 0.5
collision_interval: 0.5
length: .15

side: 1
wall_follower_velocity: 0.2
wall_follower_desired_distance: 1.

parking_controller_velocity: 0.2

line_follower_velocity: .6
line_follower_parking_distance: 0.3
line_follower_goal_range: 0.05
line_follower_y_tolerance: 0.05