# Line follower stuff
vel : 0.3
lidar_to_base_axel : -0.35
lookahead_distance : 0.75
L : 0.375

drive_topic: "vesc/ackermann_cmd_mux/input/navigation"

# Safety controller stuff

scan_topic: "/scan"
safety_topic: "/vesc/low_level/ackermann_cmd_mux/input/safety"
safety_in_topic: "/vesc/high_level/ackermann_cmd_mux/output"
drive_comm_timeout: 0.5
scan_comm_timeout: 0.5
collision_interval: 0.5
length: .15